[workspace]
resolver = "3"
members = [
    "crates/gen-types",
    "crates/gen-cargo",
    "crates/gen-config",
    "crates/gen-nix",
    "crates/gen-cache-attic",
    "crates/gen-cli",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.89.0"
license = "MIT"
homepage = "https://github.com/pleme-io/gen"
repository = "https://github.com/pleme-io/gen"
authors = ["pleme-io"]

[workspace.dependencies]
# Workspace crates
gen-types = { path = "crates/gen-types", version = "0.1.0" }
gen-cargo = { path = "crates/gen-cargo", version = "0.1.0" }
gen-config = { path = "crates/gen-config", version = "0.1.0" }
gen-nix = { path = "crates/gen-nix", version = "0.1.0" }
gen-cache-attic = { path = "crates/gen-cache-attic", version = "0.1.0" }
gen-cli = { path = "crates/gen-cli", version = "0.1.0" }

# Third-party
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_yaml = "0.9"
indexmap = { version = "2", features = ["serde"] }
thiserror = "2"
blake3 = "1"
chrono = { version = "0.4", features = ["serde"] }
toml = "0.8"
clap = { version = "4", features = ["derive"] }
shikumi = { git = "https://github.com/pleme-io/shikumi.git", rev = "a497fc03885339f169aa805f706f081da2a10e7a" }

[workspace.lints.clippy]
pedantic = { level = "warn", priority = -1 }
module_name_repetitions = "allow"
missing_errors_doc = "allow"
missing_panics_doc = "allow"

[profile.release]
codegen-units = 1
lto = true
opt-level = "z"
strip = true
