//! Per-crate Nix derivation renderer (crate2nix-compatible schema).
//! Consumes a [`gen_types::Manifest`] and emits a `Cargo.nix` that
//! `import ./Cargo.nix { inherit pkgs; }` evaluates to the standard
//! crate2nix shape: `rootCrate`, `workspaceMembers`, `internal.crates`
//! with package-name keys, edition, authors, typed dep shape,
//! sha256, procMacro, resolvedDefaultFeatures.
//!
//! The data portion (top wrapper + rootCrate + workspaceMembers +
//! `internal.crates = {...}`) is rendered through the typed
//! [`NixValue`] AST. The runtime resolver helpers
//! (`buildRustCrateWithFeatures`, `expandFeatures`, `debugCrate`, …)
//! are vendored verbatim from a crate2nix-generated file
//! (`assets/crate2nix-internal-helpers.nix`) — proven code, complex
//! enough that re-emitting them from typed source is M1+ work.

use std::collections::BTreeMap;

use gen_types::{
    DependencyKind, Manifest, Package, PackageId, PackageSource, ResolvedPackage,
};

use crate::ast::{entry, AttrSetEntry, NixValue};

/// Vendored from `pleme-io/caixa-bitflags/Cargo.nix` (crate2nix
/// 0.15.0) — the internal helper functions that drive
/// `buildRustCrateWithFeatures` + feature/dependency resolution.
/// Replace with a typed Nix template in M1+ once the renderer has
/// a real Lisp-authored source.
const INTERNAL_HELPERS: &str = include_str!("../assets/crate2nix-internal-helpers.nix");

/// Top-level entrypoint. Renders the entire `Cargo.nix` file as a
/// single String. The data portion is typed; the resolver helpers
/// are vendored.
pub fn render_workspace_to_cargo_nix(manifest: &Manifest) -> String {
    let header = render_lambda_header();
    let body = render_body(manifest);
    format!("{header}\n{body}\n")
}

/// Legacy alias — emits the typed body only (no lambda header, no
/// resolver helpers). Useful for tests that want to inspect the
/// data shape in isolation.
pub fn render_workspace(manifest: &Manifest) -> NixValue {
    build_rec_body(manifest)
}

// ── Lambda header ────────────────────────────────────────────────────

fn render_lambda_header() -> String {
    // Matches crate2nix 0.15.0's parameter list verbatim. Authored
    // here as a raw block rather than typed `LambdaParams` because
    // every consumer's Cargo.nix needs *exactly* this signature for
    // interop with `pkgs.callPackage`-shaped builders.
    r#"# Generated by gen-nix (pleme-io/gen). Compatible with crate2nix 0.15.0 schema.
{ nixpkgs ? <nixpkgs>
, pkgs ? import nixpkgs { config = {}; }
, fetchurl ? pkgs.fetchurl
, lib ? pkgs.lib
, stdenv ? pkgs.stdenv
, buildRustCrateForPkgs ? pkgs: pkgs.buildRustCrate
, defaultCrateOverrides ? pkgs.defaultCrateOverrides
, rootFeatures ? [ "default" ]
, strictDeprecation ? false
, targetFeatures ? []
, extraTargetFlags ? {}
, release ? true
, crateConfig
  ? if builtins.pathExists ./crate-config.nix
    then pkgs.callPackage ./crate-config.nix {}
    else {}
}:"#.to_string()
}

// ── Body assembly ────────────────────────────────────────────────────

fn render_body(manifest: &Manifest) -> String {
    // Render the outer wrapper with everything EXCEPT the helpers
    // section. The internal block carries `crates = ...;` as its only
    // typed entry; we then splice the helpers in via string surgery
    // before its closing `};`.
    let body = build_rec_body(manifest);
    let mut s = body.render_to_string();

    // Find the closing `};` of `internal = rec { ... };` — it's the
    // first `};` followed by a `}` line (the outer rec close). Splice
    // the helpers in just before that `};`.
    let internal_close = find_internal_close(&s).expect("internal = rec close present");
    s.insert_str(internal_close, &format!("\n{INTERNAL_HELPERS}"));
    s
}

/// Locate the byte offset of the `};` that closes
/// `internal = rec { ... }`. Strategy: find the line containing
/// `crates = {` (assumed unique inside `internal`), then walk forward
/// counting brace depth from there until we hit depth 0 — that's the
/// close of the crates attrset; the very next `};` is internal's.
fn find_internal_close(s: &str) -> Option<usize> {
    let crates_marker = s.find("crates = {")?;
    let bytes = s.as_bytes();
    let mut depth: i32 = 0;
    let mut i = crates_marker + "crates = {".len();
    // Walk to end of crates attrset (depth returns to -1 from where
    // we entered).
    while i < bytes.len() {
        match bytes[i] {
            b'{' => depth += 1,
            b'}' => {
                if depth == 0 {
                    // This `}` closes crates. Past this we expect `;`
                    // and then we're back at the top of internal's
                    // body. The next `}` we see is internal's close.
                    i += 1;
                    break;
                }
                depth -= 1;
            }
            _ => {}
        }
        i += 1;
    }
    // Now scan forward to the next `}` at internal's depth.
    let mut depth: i32 = 0;
    while i < bytes.len() {
        match bytes[i] {
            b'{' => depth += 1,
            b'}' => {
                if depth == 0 {
                    return Some(i);
                }
                depth -= 1;
            }
            _ => {}
        }
        i += 1;
    }
    None
}

fn build_rec_body(manifest: &Manifest) -> NixValue {
    NixValue::AttrSet {
        recursive: true,
        entries: vec![
            entry("rootCrate", build_root_crate(manifest)),
            entry("workspaceMembers", build_workspace_members(manifest)),
            entry("allWorkspaceMembers", build_all_workspace_members()),
            entry("internal", build_internal(manifest)),
        ],
    }
}

// ── rootCrate / workspaceMembers ─────────────────────────────────────

fn build_root_crate(manifest: &Manifest) -> NixValue {
    // The convention: rootCrate is the first workspace member (or, in
    // a single-crate repo, the only one). Caller can override by
    // configuring force_root in shikumi.
    let first = manifest.packages.first();
    match first {
        None => NixValue::AttrSet {
            recursive: true,
            entries: vec![],
        },
        Some(pkg) => NixValue::AttrSet {
            recursive: true,
            entries: vec![
                entry("packageId", NixValue::str(&pkg.name)),
                entry(
                    "build",
                    NixValue::Apply {
                        func: Box::new(NixValue::AttrPath(vec![
                            "internal".into(),
                            "buildRustCrateWithFeatures".into(),
                        ])),
                        args: vec![NixValue::AttrSet {
                            recursive: false,
                            entries: vec![AttrSetEntry::Inherit {
                                from: None,
                                names: vec!["packageId".into()],
                            }],
                        }],
                    },
                ),
                entry(
                    "debug",
                    NixValue::Apply {
                        func: Box::new(NixValue::AttrPath(vec![
                            "internal".into(),
                            "debugCrate".into(),
                        ])),
                        args: vec![NixValue::AttrSet {
                            recursive: false,
                            entries: vec![AttrSetEntry::Inherit {
                                from: None,
                                names: vec!["packageId".into()],
                            }],
                        }],
                    },
                ),
            ],
        },
    }
}

fn build_workspace_members(manifest: &Manifest) -> NixValue {
    let mut entries: Vec<AttrSetEntry> = Vec::new();
    for pkg in &manifest.packages {
        let member_attrset = NixValue::AttrSet {
            recursive: true,
            entries: vec![
                entry("packageId", NixValue::str(&pkg.name)),
                entry(
                    "build",
                    NixValue::Apply {
                        func: Box::new(NixValue::AttrPath(vec![
                            "internal".into(),
                            "buildRustCrateWithFeatures".into(),
                        ])),
                        args: vec![NixValue::AttrSet {
                            recursive: false,
                            entries: vec![entry("packageId", NixValue::str(&pkg.name))],
                        }],
                    },
                ),
                entry(
                    "debug",
                    NixValue::Apply {
                        func: Box::new(NixValue::AttrPath(vec![
                            "internal".into(),
                            "debugCrate".into(),
                        ])),
                        args: vec![NixValue::AttrSet {
                            recursive: false,
                            entries: vec![AttrSetEntry::Inherit {
                                from: None,
                                names: vec!["packageId".into()],
                            }],
                        }],
                    },
                ),
            ],
        };
        entries.push(AttrSetEntry::KeyValue {
            key: crate::ast::AttrPath(vec![crate::ast::AttrKey::Str(pkg.name.clone())]),
            value: member_attrset,
        });
    }
    NixValue::AttrSet {
        recursive: false,
        entries,
    }
}

fn build_all_workspace_members() -> NixValue {
    // Verbatim from crate2nix; never varies.
    NixValue::Raw(
        "pkgs.symlinkJoin {\n      name = \"all-workspace-members\";\n      paths =\n        let members = builtins.attrValues workspaceMembers;\n        in builtins.map (m: m.build) members;\n  }"
            .to_string(),
    )
}

// ── internal.crates table ────────────────────────────────────────────

fn build_internal(manifest: &Manifest) -> NixValue {
    let crates_table = build_crates_table(manifest);
    NixValue::AttrSet {
        recursive: true,
        entries: vec![entry("crates", crates_table)],
    }
}

fn build_crates_table(manifest: &Manifest) -> NixValue {
    // Use a sorted map keyed by package name to match crate2nix's
    // deterministic output ordering.
    let mut by_name: BTreeMap<String, CrateEntry> = BTreeMap::new();

    // Resolved (lockfile) entries → registry/git sources.
    if let Some(lock) = &manifest.lockfile {
        for resolved in lock.resolved.values() {
            by_name.insert(
                resolved.id.name.clone(),
                CrateEntry::Resolved(resolved.clone()),
            );
        }
    }
    // Workspace members override (path src + features from the
    // member's manifest).
    for pkg in &manifest.packages {
        by_name.insert(pkg.name.clone(), CrateEntry::Member(pkg.clone()));
    }

    let entries: Vec<AttrSetEntry> = by_name
        .into_iter()
        .map(|(name, e)| AttrSetEntry::KeyValue {
            key: crate::ast::AttrPath(vec![crate::ast::AttrKey::Str(name)]),
            value: render_crate(&e),
        })
        .collect();

    NixValue::AttrSet {
        recursive: false,
        entries,
    }
}

enum CrateEntry {
    Resolved(ResolvedPackage),
    Member(Package),
}

fn render_crate(e: &CrateEntry) -> NixValue {
    match e {
        CrateEntry::Resolved(r) => render_resolved_crate(r),
        CrateEntry::Member(p) => render_member_crate(p),
    }
}

fn render_resolved_crate(r: &ResolvedPackage) -> NixValue {
    let mut entries: Vec<AttrSetEntry> = Vec::new();
    entries.push(entry("crateName", NixValue::str(&r.id.name)));
    entries.push(entry("version", NixValue::str(r.id.version.to_string())));
    // edition not in ResolvedPackage today; default to 2021 — caller
    // can override via crate-config.nix. M1: enrich Lockfile with
    // edition when adapter knows it (cargo metadata).
    entries.push(entry("edition", NixValue::str("2021")));

    match &r.source {
        PackageSource::Registry { .. } => {
            if let Some(h) = &r.integrity {
                entries.push(entry("sha256", NixValue::str(strip_sha_prefix(h))));
            }
        }
        PackageSource::Git { url, rev, .. } => {
            entries.push(entry(
                "src",
                NixValue::Apply {
                    func: Box::new(NixValue::AttrPath(vec![
                        "pkgs".into(),
                        "fetchgit".into(),
                    ])),
                    args: vec![NixValue::AttrSet {
                        recursive: false,
                        entries: vec![
                            entry("url", NixValue::str(url)),
                            entry("rev", NixValue::str(rev)),
                            entry("sha256", NixValue::str(strip_sha_prefix(
                                r.integrity.as_deref().unwrap_or(""),
                            ))),
                        ],
                    }],
                },
            ));
        }
        PackageSource::Path { .. } | PackageSource::Local { .. } => {
            entries.push(entry(
                "src",
                NixValue::Apply {
                    func: Box::new(NixValue::AttrPath(vec![
                        "lib".into(),
                        "cleanSourceWith".into(),
                    ])),
                    args: vec![NixValue::AttrSet {
                        recursive: false,
                        entries: vec![
                            entry("filter", NixValue::Ident("sourceFilter".into())),
                            entry("src", NixValue::Path("./.".into())),
                        ],
                    }],
                },
            ));
        }
    }

    if !r.resolved_dependencies.is_empty() {
        entries.push(entry(
            "dependencies",
            NixValue::List(
                r.resolved_dependencies
                    .iter()
                    .map(resolved_dep_to_nix)
                    .collect(),
            ),
        ));
    }

    NixValue::AttrSet {
        recursive: true,
        entries,
    }
}

fn render_member_crate(p: &Package) -> NixValue {
    let mut entries: Vec<AttrSetEntry> = Vec::new();
    entries.push(entry("crateName", NixValue::str(&p.name)));
    entries.push(entry("version", NixValue::str(p.version.to_string())));
    entries.push(entry("edition", NixValue::str("2024")));
    entries.push(entry(
        "src",
        NixValue::Apply {
            func: Box::new(NixValue::AttrPath(vec![
                "lib".into(),
                "cleanSourceWith".into(),
            ])),
            args: vec![NixValue::AttrSet {
                recursive: false,
                entries: vec![
                    entry("filter", NixValue::Ident("sourceFilter".into())),
                    entry("src", NixValue::Path("./.".into())),
                ],
            }],
        },
    ));
    if !p.authors.is_empty() {
        entries.push(entry(
            "authors",
            NixValue::List(p.authors.iter().map(|a| NixValue::str(a)).collect()),
        ));
    }
    let runtime_deps: Vec<&gen_types::Dependency> = p
        .dependencies
        .iter()
        .filter(|d| matches!(d.kind, DependencyKind::Direct | DependencyKind::Optional))
        .collect();
    if !runtime_deps.is_empty() {
        entries.push(entry(
            "dependencies",
            NixValue::List(runtime_deps.into_iter().map(member_dep_to_nix).collect()),
        ));
    }
    let dev_deps: Vec<&gen_types::Dependency> = p
        .dependencies
        .iter()
        .filter(|d| matches!(d.kind, DependencyKind::Dev))
        .collect();
    if !dev_deps.is_empty() {
        entries.push(entry(
            "devDependencies",
            NixValue::List(dev_deps.into_iter().map(member_dep_to_nix).collect()),
        ));
    }
    let build_deps: Vec<&gen_types::Dependency> = p
        .dependencies
        .iter()
        .filter(|d| matches!(d.kind, DependencyKind::Build))
        .collect();
    if !build_deps.is_empty() {
        entries.push(entry(
            "buildDependencies",
            NixValue::List(build_deps.into_iter().map(member_dep_to_nix).collect()),
        ));
    }
    if !p.features.is_empty() {
        let feature_map_entries: Vec<AttrSetEntry> = p
            .features
            .iter()
            .map(|f| AttrSetEntry::KeyValue {
                key: crate::ast::AttrPath(vec![crate::ast::AttrKey::Str(f.name.clone())]),
                value: NixValue::List(
                    f.implies
                        .iter()
                        .map(|fr| match fr {
                            gen_types::FeatureRef::Local { name } => NixValue::str(name),
                            gen_types::FeatureRef::Namespaced { package, feature } => {
                                NixValue::str(format!("{package}/{feature}"))
                            }
                            gen_types::FeatureRef::DepActivation { dep_name } => {
                                NixValue::str(format!("dep:{dep_name}"))
                            }
                        })
                        .collect(),
                ),
            })
            .collect();
        entries.push(entry(
            "features",
            NixValue::AttrSet {
                recursive: false,
                entries: feature_map_entries,
            },
        ));
    }
    NixValue::AttrSet {
        recursive: true,
        entries,
    }
}

fn member_dep_to_nix(d: &gen_types::Dependency) -> NixValue {
    let mut entries: Vec<AttrSetEntry> = Vec::new();
    entries.push(entry("name", NixValue::str(&d.name)));
    entries.push(entry("packageId", NixValue::str(&d.name)));
    if matches!(d.kind, DependencyKind::Optional) {
        entries.push(entry("optional", NixValue::Bool(true)));
    }
    if !d.default_features {
        entries.push(entry("usesDefaultFeatures", NixValue::Bool(false)));
    }
    if !d.features_enabled.is_empty() {
        entries.push(entry(
            "features",
            NixValue::List(d.features_enabled.iter().map(|f| NixValue::str(f)).collect()),
        ));
    }
    NixValue::AttrSet {
        recursive: false,
        entries,
    }
}

fn resolved_dep_to_nix(id: &PackageId) -> NixValue {
    NixValue::AttrSet {
        recursive: false,
        entries: vec![
            entry("name", NixValue::str(&id.name)),
            entry("packageId", NixValue::str(&id.name)),
        ],
    }
}

fn strip_sha_prefix(h: &str) -> &str {
    h.strip_prefix("sha256:")
        .or_else(|| h.strip_prefix("sha512:"))
        .unwrap_or(h)
}

