//! `gen-nix-bulk` — per-tree (crane shape) bulk renderer.
//!
//! Sibling of `gen-nix`'s per-crate renderer (crate2nix shape). The
//! two ship the same typed AST + canonical pretty-printer; only the
//! derivation-shape strategy differs:
//!
//! - **gen-nix** (per-crate): one `buildRustCrate` per resolved
//!   lockfile entry. Best for incremental dev — touching one crate
//!   rebuilds only that crate's closure. Heavy on the Nix evaluator
//!   (1 derivation per crate × N crates = many derivations).
//! - **gen-nix-bulk** (per-tree): one big `craneLib.buildPackage`
//!   per workspace member, sharing one vendored source tarball. Best
//!   for CI bulk builds — fewer derivations to evaluate, but a single
//!   touched file rebuilds the whole tree.
//!
//! Operators pick the shape via `gen-config::RenderMode`. The two
//! renderers are intentionally symmetric: same input Manifest, same
//! typed NixValue output, different shape.

use gen_nix::{ast::*, NixValue};
use gen_types::{Manifest, Package};

/// Render the workspace as a per-tree (crane-shape) Nix expression.
/// Result: `{ lib, craneLib, src, ... }: { workspaceMembers = { ... }; }`.
/// Each workspace member becomes one `craneLib.buildPackage` call
/// sharing the same vendored src.
#[must_use]
pub fn render_workspace_to_crane_nix(manifest: &Manifest) -> String {
    let header = render_lambda_header();
    let body = render_body(manifest);
    format!("{header}\n{body}\n")
}

fn render_lambda_header() -> String {
    r#"# Generated by gen-nix-bulk (pleme-io/gen). Crane-shape per-tree renderer.
{ pkgs ? import <nixpkgs> { config = {}; }
, lib ? pkgs.lib
, craneLib
, src ? lib.cleanSourceWith { src = ./.; filter = path: _: !lib.hasSuffix ".nix" path; }
, buildInputs ? []
, nativeBuildInputs ? []
, release ? true
}:"#
    .to_string()
}

fn render_body(manifest: &Manifest) -> String {
    // Per-tree shape: one shared cargoArtifacts derivation, then one
    // craneLib.buildPackage per workspace member referencing that
    // shared cargoArtifacts.
    let cargo_artifacts = build_cargo_artifacts();
    let members = build_workspace_members(manifest);

    let top = NixValue::Let {
        bindings: vec![LetBinding::Bind {
            name: "cargoArtifacts".to_string(),
            value: cargo_artifacts,
        }],
        body: Box::new(NixValue::AttrSet {
            recursive: false,
            entries: vec![
                entry("workspaceMembers", members),
                entry(
                    "allWorkspaceMembers",
                    NixValue::Apply {
                        func: Box::new(NixValue::AttrPath(vec![
                            "pkgs".into(),
                            "symlinkJoin".into(),
                        ])),
                        args: vec![NixValue::AttrSet {
                            recursive: false,
                            entries: vec![
                                entry("name", NixValue::str("all-workspace-members")),
                                entry(
                                    "paths",
                                    NixValue::Raw("builtins.attrValues workspaceMembers".to_string()),
                                ),
                            ],
                        }],
                    },
                ),
            ],
        }),
    };
    top.render_to_string()
}

fn build_cargo_artifacts() -> NixValue {
    NixValue::Apply {
        func: Box::new(NixValue::AttrPath(vec![
            "craneLib".into(),
            "buildDepsOnly".into(),
        ])),
        args: vec![NixValue::AttrSet {
            recursive: false,
            entries: vec![
                AttrSetEntry::Inherit {
                    from: None,
                    names: vec!["src".into(), "buildInputs".into(), "nativeBuildInputs".into()],
                },
            ],
        }],
    }
}

fn build_workspace_members(manifest: &Manifest) -> NixValue {
    let entries: Vec<AttrSetEntry> = manifest
        .packages
        .iter()
        .map(|p| AttrSetEntry::KeyValue {
            key: AttrPath(vec![AttrKey::Str(p.name.clone())]),
            value: build_member_derivation(p),
        })
        .collect();
    NixValue::AttrSet {
        recursive: false,
        entries,
    }
}

fn build_member_derivation(p: &Package) -> NixValue {
    NixValue::Apply {
        func: Box::new(NixValue::AttrPath(vec![
            "craneLib".into(),
            "buildPackage".into(),
        ])),
        args: vec![NixValue::AttrSet {
            recursive: false,
            entries: vec![
                AttrSetEntry::Inherit {
                    from: None,
                    names: vec!["src".into(), "cargoArtifacts".into()],
                },
                entry("pname", NixValue::str(&p.name)),
                entry("version", NixValue::str(p.version.to_string())),
                entry(
                    "cargoExtraArgs",
                    NixValue::str(format!("-p {}", p.name)),
                ),
            ],
        }],
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use gen_types::*;
    use indexmap::IndexMap;

    fn demo_manifest() -> Manifest {
        let p = Package {
            name: "demo".into(),
            version: Version::new(0, 1, 0),
            source: PackageSource::Path {
                path: ".".into(),
            },
            registry: Registry::CratesIo,
            dependencies: vec![],
            features: vec![],
            build_steps: vec![],
            license: Some("MIT".into()),
            description: None,
            authors: vec![],
            homepage: None,
            repository: None,
        };
        Manifest::new(
            "/x",
            Workspace::single_package("/x", "cargo"),
            vec![p],
            None,
        )
    }

    #[test]
    fn renders_lambda_header_with_crane_inputs() {
        let m = demo_manifest();
        let s = render_workspace_to_crane_nix(&m);
        assert!(s.contains("{ pkgs ?"));
        assert!(s.contains(", craneLib"));
        assert!(s.contains(", src ?"));
    }

    #[test]
    fn renders_let_bound_cargo_artifacts() {
        let m = demo_manifest();
        let s = render_workspace_to_crane_nix(&m);
        assert!(s.contains("cargoArtifacts = craneLib.buildDepsOnly"));
    }

    #[test]
    fn renders_workspace_members_via_crane_lib_build_package() {
        let m = demo_manifest();
        let s = render_workspace_to_crane_nix(&m);
        assert!(s.contains("craneLib.buildPackage"));
        assert!(s.contains("pname = \"demo\""));
        assert!(s.contains("version = \"0.1.0\""));
        assert!(s.contains("cargoExtraArgs = \"-p demo\""));
    }

    #[test]
    fn renders_all_workspace_members_join() {
        let m = demo_manifest();
        let s = render_workspace_to_crane_nix(&m);
        assert!(s.contains("allWorkspaceMembers"));
        assert!(s.contains("symlinkJoin"));
    }

    #[test]
    fn render_is_deterministic() {
        let m = demo_manifest();
        let a = render_workspace_to_crane_nix(&m);
        let b = render_workspace_to_crane_nix(&m);
        assert_eq!(a, b);
    }

    #[test]
    fn multi_member_workspace_emits_one_entry_per_member() {
        let mut m = demo_manifest();
        m.packages.push(Package {
            name: "other".into(),
            version: Version::new(0, 2, 0),
            source: PackageSource::Path { path: ".".into() },
            registry: Registry::CratesIo,
            dependencies: vec![],
            features: vec![],
            build_steps: vec![],
            license: None,
            description: None,
            authors: vec![],
            homepage: None,
            repository: None,
        });
        let s = render_workspace_to_crane_nix(&m);
        assert!(s.contains("\"demo\""));
        assert!(s.contains("\"other\""));
        assert!(s.contains("cargoExtraArgs = \"-p other\""));
    }
}
