//! Typed build spec for Bundler — mirrors nixpkgs `bundlerEnv` /
//! `bundlerApp` kwargs so substrate's Ruby-side lockfile-builder
//! spreads the args verbatim into the builder.

use indexmap::IndexMap;
use serde::{Deserialize, Serialize};

pub const SCHEMA_VERSION: u32 = 1;

#[derive(Clone, Debug, Serialize, Deserialize, gen_macros::SpecShape)]
#[spec(
    args = "PackageArgs",
    quirk = "crate::quirks::BundlerQuirk",
    args_field = "args",
    root_field = "root_package",
    members_field = "workspace_members",
    crates_field = "packages"
)]
pub struct BuildSpec {
    pub version: u32,
    pub packages: IndexMap<String, PackageSpec>,
    pub root_package: String,
    pub workspace_members: Vec<String>,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct PackageSpec {
    pub name: String,
    pub version: String,
    pub args: PackageArgs,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub quirks: Vec<crate::quirks::BundlerQuirk>,
}

/// Pre-shaped `bundlerEnv` / `bundlerApp` kwargs. Field names match
/// nixpkgs' mkArgs signature so substrate spreads verbatim.
///
/// nixpkgs reference: `pkgs/development/ruby-modules/bundler-app`
/// + `pkgs/development/ruby-modules/bundled-common`.
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct PackageArgs {
    pub pname: Option<String>,
    pub version: Option<String>,
    /// Path (relative to source) of the `Gemfile`. Default: `./Gemfile`.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub gemfile: Option<String>,
    /// Path of the `Gemfile.lock`. Default: `./Gemfile.lock`.
    #[serde(rename = "lockfile", skip_serializing_if = "Option::is_none")]
    pub lockfile: Option<String>,
    /// Path of the gemset.nix (nixpkgs' resolved gem set). Default:
    /// `./gemset.nix` — typically generated by `bundix`.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub gemset: Option<String>,
    /// Ruby interpreter attr name (e.g. `ruby_3_3`). None = nixpkgs
    /// default (currently `ruby`).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ruby: Option<String>,
    /// Optional bundler version override.
    #[serde(rename = "bundler", skip_serializing_if = "Option::is_none")]
    pub bundler: Option<String>,
    /// Bundler groups to include (e.g. `["default", "production"]`).
    /// Default: all groups except `development` and `test`.
    #[serde(skip_serializing_if = "Vec::is_empty")]
    pub groups: Vec<String>,
    /// Names of executables the bundler env exposes via bin wrappers.
    /// `bundlerApp` requires this; `bundlerEnv` is library-only when
    /// empty.
    #[serde(skip_serializing_if = "Vec::is_empty")]
    pub exes: Vec<String>,
    /// Disable check phase. nixpkgs default is true for bundler envs.
    #[serde(rename = "doCheck", skip_serializing_if = "Option::is_none")]
    pub do_check: Option<bool>,
    /// Extra native build deps (libxml2, sqlite, etc).
    #[serde(rename = "nativeBuildInputs", skip_serializing_if = "Vec::is_empty")]
    pub native_build_inputs: Vec<String>,
    /// Runtime/link-time deps.
    #[serde(rename = "buildInputs", skip_serializing_if = "Vec::is_empty")]
    pub build_inputs: Vec<String>,
}
